### ISSUE TITLE
Exporters to support Monarch use cases

### ISSUE THREAD

**Issue by joeflack4** [biopragmatics/curies#106]
There exist ecosystem some defined formats for prefix maps. It would be nice to have `curies` exporters for those.

- [ ] SemanticSQL: `prefixes.csv`. See: https://github.com/search?q=repo%3AINCATools%2Fsemantic-sql%20prefixes.csv&type=code
- [ ] `robot --add-prefixes context.json` 
  - https://robot.obolibrary.org/global.html#prefixes
  - https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/obo_context.jsonld

**Context**: This came up originally in my work in `mondo-ingest`: https://github.com/monarch-initiative/mondolib/issues/8

**Comment by joeflack4** [comment]
@cthoyt [You mentioned](https://github.com/monarch-initiative/mondolib/issues/8#issuecomment-1900513667) it might be a good idea to solve problem (1) in either SemanticSQL or `curies` rather than in Mondo, and I think that's a great idea. Just today I noticed that (2) is another case.

**Comment by matentzn** [comment]
I think curies has an exporter for that already, something like converter.to_jsonld() or to_jsonld_context()?

**Comment by cthoyt** [comment]
Indeed, https://curies.readthedocs.io/en/latest/api/curies.write_jsonld_context.html#curies.write_jsonld_context but now I notice it needs some documentation updates
